#spring.application.name=jornal
#spring.data.mongodb.uri=mongodb+srv://rajat:12345@cluster0.2wfvvt9.mongodb.net/?appName=Cluster0
#spring.data.mongodb.database=journalnewDB
#spring.data.mongodb.auto-index-creation=true

spring:
  profiles:
    active: dev

  mail:
    host: smtp.gmail.com
    port: 587
    username: rkty075@gmail.com
    password: 5555463

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    net:
      jornal:
        journal_Application_Backend: DEBUG

weather:
  api:
    key: d988585a2a204005103c8383bde14add
