spring.application.name=jornal
spring.data.mongodb.uri=mongodb+srv://rajat:12345@cluster0.2wfvvt9.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=journalnewDB
spring.data.mongodb.auto-index-creation=true